version: "3"
services:
  catalog:
    image: jasmine-psql:0.1
    container_name: "jasmine"
    build: ./psql
    ports:
      - "15432:5432"
    sysctls:
      kernel.sem: 50100 128256000 50100 2560
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "jasmine"
      POSTGRES_PASSWORD: "jasmine"
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - "./data/catalog:/data/catalog:ro"
      - "./data/postgresql/:/var/lib/postgresql/data:rw"
